### ISSUE TITLE
Issue with CW3 and Custom Attributes

### ISSUE THREAD

**Issue by Thefuzz1234555** [nosoop/SM-TFCustomAttributeStarterPack#24]
Whenever I try using a weapon that has a custom attribute it'll show a error in the console,

[CW3 Attributes] WARNING! Attribute "medigun drains health" (value "50.000000" plugin "custom-attribute-adapter/joke_medigun_mod_drain_health") seems to have been ignored by all attribute plugins. It's either an invalid attribute, incorrect plugin, an error occured in the att. plugin, or the att. plugin forgot to return Plugin_Handled.

I'm pretty confused on to why this is happening I'm pretty certain I put everything in the correct file location

**Comment by nosoop** [comment]
There's a number of reasons why you'd get that error:

- [The core Custom Attributes plugin isn't installed.](https://github.com/nosoop/SM-TFCustAttr/releases)  It is a completely separate system from Custom Weapons.
- [The Custom Weapon Adapter isn't installed.](https://github.com/nosoop/SM-TFCustAttr/wiki/Applying-Custom-Attributes#with-custom-weapons-2--custom-weapons-3)
- The adapter is installed, but `joke_medigun_mod_drain_health.smx` is either missing or not successfully loading.  In this case, you'll also get a message that says "Could not find required attribute plugin joke_medigun_mod_drain_health" &mdash; at that point you'll have to try to load that plugin.

Please make sure you've installed all the required dependencies, and that you've verified that they're up and running &mdash; [this Discord conversation](https://discordapp.com/channels/335290997317697536/335290997317697536/721260929206976576) and [this discussion in the CW3 topic](https://forums.alliedmods.net/showpost.php?p=2706277&postcount=233) should cover all the troubleshooting instructions I've given so far.

**Comment by Thefuzz1234555** [comment]
All dependencies are there, Adapter was missing but it's installed now however I'm getting this in the console now, 

[custom-attribute-adapter/custom_lunchbox_effect.smx] Custom lunchbox effect 'sugar frenzy' is not associated with a plugin

In the applying custom attributes area I don't really understand what 3 in the CW3 section is talking about, also I can't see the discord conversation because I'm not in the Discord

**Comment by nosoop** [comment]
```
[custom-attribute-adapter/custom_lunchbox_effect.smx] Custom lunchbox effect 'sugar frenzy' is not associated with a plugin
```
That means you are trying to use an item that has that custom lunchbox effect, but the plugin that provides it isn't loaded in, specifically `plugins/custom-attr-starter-pack/lunchbox_effects/sugar_frenzy.smx`.

(3) means that the plugin name can either be `custom-attribute-adapter`, or `custom-attribute-adapter/${PLUGIN_NAME}`, where `${PLUGIN_NAME}` is the name of a plugin that must be loaded (otherwise the adapter will report an error matching my third bullet point above).

The Discord conversation is on [the AlliedModders guild](https://discord.gg/HUc67zN).

**Comment by Thefuzz1234555** [comment]
That seems to have fixed everything for the most part, there are certain custom weapons such as the air lock that don't actually do anything it seems, I'll close this for now because that seems to have fixed everything, Thank you for your time

**Comment by nosoop** [comment]
There is a mistake specifically in the Air Lock configuration (the adapter should be printing a warning that it `Could not find a weapon in slot 1 to apply 'demo charge low gravity'.`, which is due to CW3 attributes normally operating on a slot instead of an entity).

I suppose I should fix that at some point once I'm finished with my break, been fielding a lot of questions lately.
