### ISSUE TITLE
Four separate attribute plugins do not load

### ISSUE THREAD

**Issue by SoulBlast35** [nosoop/SM-TFCustomAttributeStarterPack#37]
**Initial troubleshooting checklist**
- [x] The attribute is loaded, or this bug report is about a plugin load failure.  (Check `sm plugins list` on the server.)

**Describe the bug**
This affects four attribute plugins, three with the same error that prevents them from starting, all of which seem to point to DHooks being the issue:
- attr_group_overheal_uber - Invalid Handle 0
- keep_disguise_on_attack - Invalid Handle 0
- lunchbox_override_pickup_type - Invalid Handle 0
generate_rage_on_damage_patch throws something different, but also seems to be related to DHookEnableDetour: "Could not verify patch for HandleRageGain()::NoHeavyRageGain"

**To Reproduce**
Simply attempt to load these plugins either on Server start or through "sm plugins load". I have DetourEnabledDHooks installed, as well as every dependency the Starter Pack needs.

**Expected behavior**
They should have loaded. For some reason, I dont remember these plugins ever throiwng this error before when I first used the Starter Pack.

**Server environment (please complete the following information):**
 - Operating System: Windows 10
 - SourceMod version: 1.10.0.6502

**Comment by nosoop** [comment]
All four of those are known to be either unsupported or problematic on Windows; see issues #7, #12, #21, and #22.
The invalid handle being vague is also tracked at issue #31.

**Comment by SoulBlast35** [comment]
Ah I see. God I need to learn Linux... ._.

**Comment by nosoop** [comment]
`attr_group_overheal_uber` signature might just be outdated, but since I can't seem to pin down exactly how it's crashing on that platform, there's not much point in fixing it since it's unreliable anyways.  `keep_disguise_on_attack` should be usable from the game directly after [attribute injection](https://forums.alliedmods.net/showthread.php?t=326853), and the others are basically "someone can donate their time or pay me to fix it" issues since they're a pain to maintain.

If you have the hardware capacity (and time) to spare, VirtualBox is a good way to start experimenting with Linux!
With less time, I think [Open Game Panel](https://opengamepanel.org/news.php) or [Pterodactyl[(https://pterodactyl.io/) would get you a working TF2 server, but I've never used them myself so I can't personally endorse either.  ([I don't think you need that much knowledge to get a server running without either.](https://wiki.teamfortress.com/wiki/Linux_dedicated_server))

Anyways, since these are all known issues, I'll go ahead and close this one.  That said, I very much appreciate the effort put into the report.
